// app/berita/page.tsx
"use client";

import { useState, useMemo } from "react";
import Card from "@/components/ui/Card";
import { newsData } from "@/constants/dummy";

const BeritaPage = () => {
  const [searchQuery, setSearchQuery] = useState("");

  // Filter news based on search query
  const filteredNews = useMemo(() => {
    if (!searchQuery.trim()) return newsData;
    return newsData.filter((news) =>
      news.title.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery]);

  return (
    <div className="w-full flex flex-col min-h-screen bg-white relative overflow-hidden py-16">

      {/* Header Section */}
      <div className="w-full flex flex-col items-center pb-8 px-4 relative z-10">
        <h1 className="text-title-2 text-darker-2 text-center mb-4">
          Berita dari Padukuhan Pondok
        </h1>
        <p className="text-regular-5 text-primary-6 text-center max-w-4xl leading-relaxed">
          berbagai informasi dan kabar terbaru dari Padukuhan Pondok. Berita yang ditampilkan meliputi kegiatan masyarakat, acara seni dan budaya, kegiatan keagamaan, program pembangunan, hingga berbagai aktivitas sosial yang melibatkan warga.
        </p>
      </div>

      {/* Search Bar */}
      <div className="w-full flex justify-center px-4 mb-8 relative z-10">
        <div className="relative w-full max-w-md">
          <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
            <svg
              className="w-5 h-5 text-gray-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </div>
          <input
            type="text"
            placeholder="Search..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-12 pr-4 py-3 border border-gray-6 rounded-lg text-regular-5 focus:outline-none focus:ring-2 focus:ring-primary-1 focus:border-transparent transition-all duration-300 bg-white shadow-sm"
          />
        </div>
      </div>

      {/* News Grid */}
      <div className="w-full max-w-6xl mx-auto px-4 pb-16 relative z-10">
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 md:gap-6">
          {filteredNews.map((news) => (
            <Card
              key={news.id}
              variant="ghost"
              imageUrl={news.image}
              title={news.title}
              date={news.date}
            />
          ))}
        </div>

        {/* No Results Message */}
        {filteredNews.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16">
            <svg
              className="w-16 h-16 text-gray-5 mb-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={1.5}
                d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <p className="text-regular-5 text-gray-4">
              Tidak ada berita yang ditemukan
            </p>
            <button
              onClick={() => setSearchQuery("")}
              className="mt-4 text-primary-1 text-regular-4 hover:text-primary-2 transition-colors duration-300 flex items-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
              Hapus pencarian
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default BeritaPage;

// resources/js/Pages/Berita.vue
<script setup>
import { Head, Link } from '@inertiajs/vue3';
import MainLayout from '@/Layouts/MainLayout.vue';
import BeritaHomeCard from '@/Components/BeritaHomeCard.vue';

defineProps({
  berita: Object,
});

const formatDate = (date) => {
  return new Date(date).toLocaleDateString('id-ID', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
};
</script>

<template>
    <Head title="Berita" />

    <MainLayout>
        <div class="flex flex-col justify-center items-center py-16 px-40 gap-14">
            <div class="flex flex-col justify-center items-center gap-10">
                <div class="flex flex-col justify-center items-center gap-5">
                    <h1 class="title-2">
                        Berita dari Padukuhan Pondok
                    </h1>
                    <p class="medium-5 text-center text-primary-6">
                        berbagai informasi dan kabar terbaru dari Padukuhan Pondok. Berita yang ditampilkan meliputi kegiatan masyarakat, <br />
                        acara seni dan budaya, kegiatan keagamaan, program pembangunan, hingga berbagai aktivitas sosial yang melibatkan <br />
                        warga.
                    </p>
                </div>
                <input 
                    type="text"
                    placeholder="Search"
                    class="w-[600px] input py-3 px-6 border-1 border-white-3 rounded-full"
                />
            </div>

            <div class="grid grid-cols-4 gap-9">
                <BeritaHomeCard
                    v-for="berita in berita.data"
                    :key="berita.id"
                    :id="berita.id"
                    :title="berita.judul"
                    :description="berita.konten.substring(0, 100) + '...'"
                    :imageUrl="berita.gambar ? `/storage/${berita.gambar}` : '/images/home_title_clip_image.png'"
                    :date="formatDate(berita.created_at)"
                />
            </div>

            <!-- Pagination -->
            <!-- <div v-if="berita.links" class="mt-8">
                <nav class="flex items-center justify-between">
                    <div class="flex-1 flex justify-between sm:hidden">
                        <Link
                            v-if="berita.links.prev"
                            :href="berita.links.prev"
                            class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
                        >
                            Previous
                        </Link>
                        <Link
                            v-if="berita.links.next"
                            :href="berita.links.next"
                            class="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
                        >
                            Next
                        </Link>
                    </div>
                    <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
                        <div>
                            <p class="text-sm text-gray-700">
                                Showing {{ berita.from }} to {{ berita.to }} of {{ berita.total }} results
                            </p>
                        </div>
                        <div>
                            <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px">
                                <template v-for="(link, index) in berita.links" :key="index">
                                    <Link
                                        v-if="link.url"
                                        :href="link.url"
                                        v-html="link.label"
                                        class="relative inline-flex items-center px-4 py-2 border text-sm font-medium"
                                        :class="link.active ? 'z-10 bg-indigo-50 border-indigo-500 text-indigo-600' : 'bg-white border-gray-300 text-gray-500 hover:bg-gray-50'"
                                    />
                                    <span
                                        v-else
                                        v-html="link.label"
                                        class="relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-700"
                                    />
                                </template>
                            </nav>
                        </div>
                    </div>
                </nav>
            </div> -->
        </div>
    </MainLayout>
</template>
